### ISSUE TITLE
very bad design

### ISSUE THREAD

**Issue by quantenschaum** [pimoroni/cap1xxx#14]
This is related to [touchphat #5](https://github.com/pimoroni/touch-phat/issues/5).

### What is wrong with `cap1xxx`?

1. **Hardware detection** There is [code for detecting the chip used](https://github.com/pimoroni/cap1xxx/blob/be4f15526abc4cf895a4dd3c07005f9c49c94b73/library/cap1xxx.py#L652). Why is it not used to automatically instantiate the right class?
1. **Polling** The CAP1166's state [is polled constantly](https://github.com/pimoroni/cap1xxx/blob/be4f15526abc4cf895a4dd3c07005f9c49c94b73/library/cap1xxx.py#L372), if no IRQ line is configured. This happens at a pretty high rate and the sleep delay is hardcoded. The method name `wait_for_interrupt` is a misnomer. You **never** wait for an interrupt by polling. This is the complete opposite of an interrupt. What is happening here, is polling the state change latch register.
1. If the hardware interrupt is used, which is impossible on the touchphat without modifying the hardware, the [interrupt handler does way too much](https://github.com/pimoroni/cap1xxx/blob/be4f15526abc4cf895a4dd3c07005f9c49c94b73/library/cap1xxx.py#L393). `_handle_alert` does everything, an interrupt handler should only set a flag and return asap. The actually processing of the assigned action as to happen on a different thread. And what is the rationale for the 1 second bouncetime? The IRQ line does not bounce! This just makes it unresponsive.
1. Setting the [led behaviour](https://github.com/pimoroni/cap1xxx/blob/be4f15526abc4cf895a4dd3c07005f9c49c94b73/library/cap1xxx.py#L549) is broken with a float as register address.

There are more deficiencies. It's a good start, but this library has to be reworked thoroughly.

**Comment by Gadgetoid** [comment]
1. some products have multiple ICs. Explicit is better than implicit.

2. It's waiting for the interrupt bit to flip in the IC. Semantics. Potato potato etc!

3. It works. There's no pressing need to change that for the sake of correctness.

4. Might be a good idea to raise a separate issue for this on the cap1xxx git. Granted since this library was written to underpin our own product libraries it's not an huge issue.

I appreciate your concern, and there are plenty of things that bug me about the library. Unfortunately time is precious and I can't afford to waste it fixing something that works well enough.
