### ISSUE TITLE
incorrect bus probing?

### ISSUE THREAD

**Issue by RogueM** [pimoroni/cap1xxx#7]
reported here:
http://forums.pimoroni.com/t/solved-explorerphat-pi3-archlinux-product-id-5-not-supported/2705

can't really see anything in the code what would return a value from the register without a cap found at 0x28...

**Comment by Gadgetoid** [comment]
I'm guessing a -N would be the value/error code returned upon error when reading a register? It's not very pythonic, but since it's hooking into underlying C code I guess it doesn't have much choice.

Worth a delve into the underlying library to find out what the negative error codes mean, it may be prudent to catch and act upon them. Aannnd here's the relevant line (I think, smbus is a bit of a rabbit hole)- http://lxr.free-electrons.com/source/drivers/i2c/i2c-core.c#L2723

``` c
2723 s32 i2c_smbus_read_byte_data(const struct i2c_client *client, u8 command)
2724 {
2725         union i2c_smbus_data data;
2726         int status;
2727 
2728         status = i2c_smbus_xfer(client->adapter, client->addr, client->flags,
2729                                 I2C_SMBUS_READ, command,
2730                                 I2C_SMBUS_BYTE_DATA, &data);
2731         return (status < 0) ? status : data.byte;
2732 }
```

And if we delve a little deeper:

http://lxr.free-electrons.com/source/include/uapi/asm-generic/errno-base.h#L8

```
  8 #define EIO              5      /* I/O error */
```

So I'm not 100% sure, but I'm going to hazard a guess that the -5 value return is an EIO or I/O Error. Presumably this is linked to the previous issue mentioned by this user about IOError (being merged into IOError!?) - anyway, if Python isn't failing with an IOError then apparently you end up with a -5 value.

I'm not sure there's anything to fix here, but clearly Python 3.5 will give us some things to think about.
